eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka,http://localhost:9075/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    appname: ${spring.application.name}
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    instanceId: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    
management:
    security:
        enabled: false