spring:
    boot:
        admin:
            url = http://localhost:8072
            

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka,http://localhost:9075/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    appname: ${spring.application.name}
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    instanceId: ${spring.application.name}:${random.value}