server:
  port: 8071

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    instanceId: ${spring.application.name}:${random.value}
  client:
    defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jtalm/spring-cloud-config